### ISSUE TITLE
How to find value for process.env.SECURE_COOKIE

### ISSUE THREAD

**Issue by jagyas** [vgrafe/nextjs-auth0-hasura#6]
Hello @vgrafe ,
From where I can get value of process.env.SECURE_COOKIE?
Is this will be found at Auth0?
Can we hit Hasura without setting Admin key in header?
How JWT claims in JSON are converting to JWT format?

I am new to this JWT :)
Thanks for help!

**Comment by vgrafe** [comment]
Hi! 

`SECURE_COOKIE` just holds a boolean value, to set to `true` if you want the cookie to be persisted on https only.

Once you get your response from auth0, you don't need to have an admin key in headers, as the JWT holds info on both authentication and authorizations

Not sure how to answer your last question.

This repo is not maintained actively anymore, sorry about that!

**Comment by jagyas** [comment]
@vgrafe Thanks a lot for help! :)
